name: Build Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  cross_build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller paho-mqtt
      - name: Build Executable
        run: pyinstaller --onefile open-mqtt-broadcaster-client.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mqtt-broadcaster-${{ matrix.os }}
          path: dist/open-mqtt-broadcaster-client*

  arch_build:
    name: Build Executable on Arch Linux
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v2
      - name: Update system and install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm python python-pip python-virtualenv base-devel
      - name: Install pip dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install pyinstaller paho-mqtt
      - name: Build Executable
        run: |
          source venv/bin/activate
          pyinstaller --onefile open-mqtt-broadcaster-client.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mqtt-broadcaster-arch
          path: dist/open-mqtt-broadcaster-client*

  create_release:
    name: Create Release
    needs: [cross_build, arch_build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mqtt-broadcaster-ubuntu-latest/*
            mqtt-broadcaster-windows-latest/*
            mqtt-broadcaster-macos-latest/*
            mqtt-broadcaster-arch/*
          draft: false
          prerelease: false
          generate_release_notes: true 