name: Build Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  cross_build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller paho-mqtt tk
      - name: Build Executable
        if: runner.os != 'macOS'
        run: pyinstaller --onefile --hidden-import tkinter --hidden-import paho.mqtt.client --hidden-import json --hidden-import threading --hidden-import queue --hidden-import datetime --hidden-import logging open-mqtt-broadcaster-client.py
      - name: Build macOS App
        if: runner.os == 'macOS'
        run: |
          pyinstaller --windowed --name "MQTT Broadcaster" \
            --hidden-import tkinter \
            --hidden-import paho.mqtt.client \
            --hidden-import json \
            --hidden-import threading \
            --hidden-import queue \
            --hidden-import datetime \
            --hidden-import logging \
            open-mqtt-broadcaster-client.py
          cd dist
          hdiutil create -volname "MQTT Broadcaster" -srcfolder "MQTT Broadcaster.app" -ov -format UDZO "MQTT-Broadcaster-macos.dmg"
      - name: Rename executable for platform
        shell: bash
        run: |
          cd dist
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            mv open-mqtt-broadcaster-client.exe "MQTT-Broadcaster-Windows.exe"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            mv "MQTT-Broadcaster-macos.dmg" "MQTT-Broadcaster-macOS.dmg"
          else
            mv open-mqtt-broadcaster-client "MQTT-Broadcaster-Ubuntu.AppImage"
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mqtt-broadcaster-${{ matrix.os }}
          path: dist/MQTT-Broadcaster-*

  arch_build:
    name: Build Executable on Arch Linux
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v2
      - name: Update system and install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm python python-pip python-virtualenv base-devel tk
      - name: Install pip dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install pyinstaller paho-mqtt tk
      - name: Build Executable
        run: |
          source venv/bin/activate
          pyinstaller --onefile --hidden-import tkinter --hidden-import paho.mqtt.client --hidden-import json --hidden-import threading --hidden-import queue --hidden-import datetime --hidden-import logging open-mqtt-broadcaster-client.py
      - name: Rename executable for Arch
        run: |
          cd dist
          mv open-mqtt-broadcaster-client "MQTT-Broadcaster-Arch.AppImage"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mqtt-broadcaster-arch
          path: dist/MQTT-Broadcaster-*

  create_release:
    name: Create Release
    needs: [cross_build, arch_build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./mqtt-broadcaster-ubuntu-latest/MQTT-Broadcaster-Ubuntu.AppImage
            ./mqtt-broadcaster-windows-latest/MQTT-Broadcaster-Windows.exe
            ./mqtt-broadcaster-macos-latest/MQTT-Broadcaster-macOS.dmg
            ./mqtt-broadcaster-arch/MQTT-Broadcaster-Arch.AppImage
          draft: false
          prerelease: false
          generate_release_notes: true 