name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output_name: mqtt-broadcaster-linux
          - os: windows-latest
            output_name: mqtt-broadcaster-windows.exe
          - os: macos-latest
            output_name: mqtt-broadcaster-macos

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-xinerama0 libgl1-mesa-dev

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name ${{ matrix.output_name }} qt_mqtt_broadcaster.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output_name }}
        path: dist/${{ matrix.output_name }}*
        retention-days: 5

  create_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          mqtt-broadcaster-linux/mqtt-broadcaster-linux
          mqtt-broadcaster-windows.exe/mqtt-broadcaster-windows.exe
          mqtt-broadcaster-macos/mqtt-broadcaster-macos
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}