name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            output_name: mqtt-broadcaster
            pkg_type: appimage
            pkg_ext: AppImage
          - os: windows-latest
            output_name: mqtt-broadcaster
            pkg_type: win
            pkg_ext: exe
          - os: macos-latest
            output_name: mqtt-broadcaster
            pkg_type: mac
            pkg_ext: dmg

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install Linux Build Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-xinerama0 libgl1-mesa-dev

    - name: Install Packaging Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev rubygems build-essential zstd rpm fakeroot imagemagick
        sudo gem install --no-document fpm

    - name: Install AppImage Tools
      if: matrix.pkg_type == 'appimage'
      run: |
        sudo apt-get update
        sudo apt-get install -y fuse libfuse2
        wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        # Extract AppImageTool to avoid FUSE issues
        ./appimagetool-x86_64.AppImage --appimage-extract
        sudo mv squashfs-root /opt/appimagetool
        sudo ln -s /opt/appimagetool/AppRun /usr/local/bin/appimagetool

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed \
          --name ${{ matrix.output_name }} \
          --add-data "README.md:." \
          --hidden-import=PyQt6.sip \
          --hidden-import=paho.mqtt.client \
          qt_mqtt_broadcaster.py

    - name: Install Additional Dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        pip install pywin32-ctypes

    - name: Create Debian Package
      if: matrix.pkg_type == 'deb'
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
        mkdir -p deb-pkg/usr/bin deb-pkg/usr/share/applications deb-pkg/usr/share/icons/hicolor/256x256/apps
        cp dist/${{ matrix.output_name }} deb-pkg/usr/bin/mqtt-broadcaster
        
        # Create desktop entry
        cat > deb-pkg/usr/share/applications/mqtt-broadcaster.desktop << EOF
        [Desktop Entry]
        Name=MQTT Broadcaster
        Comment=MQTT client for testing and debugging
        Exec=mqtt-broadcaster
        Icon=mqtt-broadcaster
        Terminal=false
        Type=Application
        Categories=Network;Qt;
        EOF
        
        # Create icon
        convert -size 256x256 xc:transparent -font DejaVu-Sans -pointsize 24 -gravity center \
          -draw "text 0,0 'MQTT'" -draw "text 0,30 'Broadcaster'" \
          deb-pkg/usr/share/icons/hicolor/256x256/apps/mqtt-broadcaster.png
        
        fpm -s dir -t deb \
          -C deb-pkg \
          -n mqtt-broadcaster \
          -v ${VERSION} \
          --description "MQTT client for testing and debugging" \
          --url "https://github.com/encomjp/Open-MQTT-Broadcaster" \
          --maintainer "encom" \
          --license "MIT" \
          --architecture "amd64" \
          --depends "python3" \
          --depends "python3-qt6" \
          --depends "python3-paho-mqtt" \
          --deb-priority "optional" \
          --deb-no-default-config-files

    - name: Create AppImage
      if: matrix.pkg_type == 'appimage'
      run: |
        # Create proper AppDir structure
        mkdir -p AppDir/usr/{bin,share/{applications,icons/hicolor/256x256/apps}}
        cp dist/${{ matrix.output_name }} AppDir/usr/bin/
        chmod +x AppDir/usr/bin/${{ matrix.output_name }}
        
        # Generate valid AppStream metadata
        cat > AppDir/usr/share/metainfo/mqtt-broadcaster.appdata.xml << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <component type="desktop-application">
          <id>mqtt-broadcaster</id>
          <name>MQTT Broadcaster</name>
          <summary>MQTT client for testing and debugging</summary>
          <metadata_license>MIT</metadata_license>
          <project_license>MIT</project_license>
          <description>
            <p>A powerful and user-friendly MQTT client application built with Python and Qt</p>
          </description>
          <categories>
            <category>Network</category>
            <category>Qt</category>
          </categories>
        </component>
        EOF
        
        # Build AppImage
        appimagetool AppDir mqtt-broadcaster-${{ env.VERSION }}-${{ matrix.pkg_type }}.AppImage

    - name: Set Version (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $env:VERSION = "${{ github.ref_name }}" -replace '^v',''
        echo "VERSION=$env:VERSION" >> $env:GITHUB_ENV

    - name: Set Version (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Rename and Move Artifacts
      run: |
        mv dist/${{ matrix.output_name }} mqtt-broadcaster-${{ env.VERSION }}-${{ matrix.pkg_type }}.${{ matrix.pkg_ext }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mqtt-broadcaster-${{ matrix.pkg_type }}
        path: mqtt-broadcaster-*.${{ matrix.pkg_ext }}
        retention-days: 5

  create_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          mqtt-broadcaster-${{ env.VERSION }}-appimage.AppImage
          mqtt-broadcaster-${{ env.VERSION }}-win.exe
          mqtt-broadcaster-${{ env.VERSION }}-mac.dmg
        body: |
          MQTT Broadcaster ${{ env.VERSION }}
          
          Downloads:
          - Windows: mqtt-broadcaster-${{ env.VERSION }}-win.exe
          - macOS: mqtt-broadcaster-${{ env.VERSION }}-mac.dmg
          - Linux:
            - AppImage: mqtt-broadcaster-${{ env.VERSION }}-appimage.AppImage
          
          ### Installation
          
          #### Windows
          Download and run the .exe file
          
          #### macOS
          1. Download the .dmg file
          2. Mount the DMG image
          3. Drag MQTT Broadcaster to Applications
          
          #### Linux
          - AppImage: Download, make executable (`chmod +x`) and run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}